services:

  influxdb2:
    container_name: influxdb2
    image: "influxdb:2-alpine"
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      # - DOCKER_INFLUXDB_INIT_MODE=upgrade
    ports:
      - "8086:8086"
    volumes:
      - ./volumes/influxdb2/data:/var/lib/influxdb2
      - ./volumes/influxdb2/config:/etc/influxdb2
      - ./volumes/influxdb2/backup:/var/lib/backup
      # - ./volumes/influxdb.migrate/data:/var/lib/influxdb:ro
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
